### ISSUE TITLE
libprotobuf ERROR google/protobuf/text_format.cc:245

### ISSUE THREAD

**Issue by songjun54cm** [rbgirshick/fast-rcnn#1]
I compile the code following the guide, and when I try to run the demo from tools/demo.py, the error occurred:

libdc1394 error: Failed to initialize libdc1394
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0501 11:01:21.328140 11559 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/VGG16/test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

I think there is something wrong with the prototxt or the pre-trained model.
How can I fix this problem?

**Comment by rbgirshick** [comment]
My guess is that you have another installation of Caffe already in your PYTHONPATH. You'll need to use the included caffe-fast-rcnn git submodule, which defines a couple of new layers, including the RoI pooling layer.

**Comment by songjun54cm** [comment]
Thank you very much!
Because i clone the caffe-fast-rcnn by hand, so it is not on the correct branch.
After checking out the fast-rcnn branch and re-compiling the code, the error is gone.

**Comment by rbgirshick** [comment]
Good to hear.

**Comment by xprincehf** [comment]
hi, I have the same error as you,  how do you re-compile the code, I recompile under the caffe-fast-rcnn root as caffe install guide,but  after that ,the error still exist.

**Comment by songjun54cm** [comment]
As I have explained, I check out the correct branch and then recompile the code, the error was gone.
I think you should to check that you checked out the correct branch fast-rcnn in the caffe-fast-rcnn root.

**Comment by TRotK** [comment]
I am not quite familiar with git. Could you please explain it more specifically? Thanks a lot!

**Comment by TRotK** [comment]
I ran "git checkout master" on my current caffe-fast-rcnn root. Before recompiling, I do "make clean". However the following error occurs: 
/bin/sh: /usr/local/cuda/bin/nvcc: No such file or directory
(standard_in) 1: parse error

Then I keep moving on, "make all", "make runtest"... No more error occurs. When I try to run the demo again, I however still encounter the same error as before:

$ ./tools/demo.py --cpu
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0720 21:37:12.831410 1969263360 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /Users/TRotK/fast-rcnn/models/VGG16/test.prototxt
*** Check failure stack trace: ***
Abort trap: 6 

Any suggestion is appreciated!

**Comment by flipflop98** [comment]
Hi,

I have similar situation with above.
I'm using caffe-fast-rcnn the sam with fast-rcnn.
But I have following error when playing demo.py as follows.
ch723.kim@ubuntu:~/samba/py-faster-rcnn-master$ ./tools/demo.py
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 310:18: Message type "caffe.LayerParameter" has no field named "reshape_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1205 21:22:31.945125 17247 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/ch723.kim/samba/py-faster-rcnn-master/models/VGG16/faster_rcnn_alt_opt/faster_rcnn_test.pt
*** Check failure stack trace: ***
Aborted (core dumped)


Also I have the same error when I run "./experiments/scripts/faster_rcnn_alt_opt.sh 3 ZF" as follows.
I1205 21:16:10.417134 17205 solver.cpp:32] Initializing solver from parameters: 
train_net: "models/ZF/faster_rcnn_alt_opt/stage1_rpn_train.pt"
base_lr: 0.001
display: 20
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 60000
snapshot: 0
snapshot_prefix: "zf_rpn"
average_loss: 100
I1205 21:16:10.417202 17205 solver.cpp:61] Creating training net from train_net file: models/ZF/faster_rcnn_alt_opt/stage1_rpn_train.pt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 221:18: Message type "caffe.LayerParameter" has no field named "reshape_param".
F1205 21:16:10.417758 17205 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/ZF/faster_rcnn_alt_opt/stage1_rpn_train.pt
*** Check failure stack trace: ***
Please give me any suggestion.

Thank you.

**Comment by Mhalla** [comment]
Hello,
I want to start with Fast RCNN but I have this  error


linux@linux-XPS-630i:~/FRCN_ROOT$ ./tools/demo.py --cpu
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 4:13: Message type "caffe.NetParameter" has no field named "input_shape".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1206 20:10:44.134786 28081 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/linux/FRCN_ROOT/models/VGG16/test.prototxt
*** Check failure stack trace: ***
Abandon (core dumped)


Don't really know how to fix this error. I Hope you can help me.
![capture du 2015-12-06 20 28 56](https://cloud.githubusercontent.com/assets/12150965/11615220/7131f024-9c5b-11e5-8da9-8582650970b7.png)

**Comment by oversnowgrass** [comment]
I have similar situation with above.When i run python demo.py --cpu,I have the error :+1: 

C:\Users\Administrator>f:
F:\>cd caffe\fast-rcnn-master\tools
F:\caffe\fast-rcnn-master\tools>python demo.py --cpu
D:\caffe\caffe-master\Build\x64\Release\pycaffe\caffe\pycaffe.py:13: Runtime
[libprotobuf ERROR ..\src\google\protobuf\text_format.cc:274] Error parsing text
-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no f
ield named "roi_pooling_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0516 08:40:48.301647  5344 upgrade_proto.cpp:79] Check failed: ReadProtoFromTex
tFile(param_file, param) Failed to parse NetParameter file: F:\caffe\fast-rcnn-m
aster\models\VGG16\test.prototxt
*** Check failure stack trace: ***

F:\caffe\fast-rcnn-master\tools>

I have found lots of solution but still don't solve it.Please can you help me?This is my fast-rcnn folder:
![qq 20160516092511](https://cloud.githubusercontent.com/assets/19328128/15278235/3ab64970-1b48-11e6-8199-81c3e49e00c5.png)

**Comment by Mhalla** [comment]
Hello,

You have a problem in the  download of fast RCNN, you must use this command
for donlowed the fast RCNN (git clone --recursive
https://github.com/rbgirshick/fast-rcnn.git), because you have
incompatibility between caffe and Fast RCNN (you dowlonded Fast with
Download Zip? )

2016-05-16 3:26 GMT+02:00 oversnowgrass <notifications@github.com>:

**Comment by oversnowgrass** [comment]
Thank you for your letter while sleeping.I have downloaded the fast-rcnn in the right way,but it still appear the problem 
![abec245fa7c8493726e52299275dd84b](https://cloud.githubusercontent.com/assets/19328128/15316311/f70beb46-1c4e-11e6-91a5-d53bf8880577.png)
![040acdc2 92699a3f_299f3957_recompress](https://cloud.githubusercontent.com/assets/19328128/15316327/05123aba-1c4f-11e6-82d4-451d76ef51ef.jpg)
Do you think there have any other solution to the problem?I'm looking forward to your letter.

**Comment by sarkeribrahim** [comment]
how to solve this ?
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0718 17:01:06.813407 26562 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0718 17:01:06.813459 26562 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0718 17:01:06.813477 26562 _caffe.cpp:125] Net('/home/rvlab/Documents/fast-rcnn-master/models/VGG16/test.prototxt', 1, weights='/home/rvlab/Documents/fast-rcnn-master/data/fast_rcnn_models/vgg16_fast_rcnn_iter_40000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
F0718 17:01:06.815565 26562 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/rvlab/Documents/fast-rcnn-master/models/VGG16/test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped

**Comment by dawin2015** [comment]
hi,@rbgirshick @songjun54cm 
I am in China where some places cannot use the `git clone --recursive https://github.com/rbgirshick/fast-rcnn.git`. Once I did that, it would print time run out error. So I manually downloaded your zip `fast-rcnn-master.zip` and unzip into the file `FRCN_ROOT`. Then I followed your  README.md and began from "3.Build the Cython modules": `cd $FRCN_ROOT/lib &&make`. Everything was fine except for this
 `dawin@dawin-Lenovo:~/Downloads/FRCN_ROOT$ sudo ./tools/demo.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0829 15:08:30.115890  7010 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0829 15:08:30.115929  7010 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0829 15:08:30.115936  7010 _caffe.cpp:125] Net('/home/dawin/Downloads/FRCN_ROOT/models/VGG16/test.prototxt', 1, weights='/home/dawin/Downloads/FRCN_ROOT/data/fast_rcnn_models/vgg16_fast_rcnn_iter_40000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
F0829 15:08:30.118136  7010 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/dawin/Downloads/FRCN_ROOT/models/VGG16/test.prototxt
*** Check failure stack trace: ***`
I had read all the blogs here and I tried, but I cannot figure out how to deal it.
I would appreciate your suggestions.

**Comment by lindylin1817** [comment]
You could directly check the src/caffe/proto/caffe.proto. If you couldn't find anything with "ROI", you could add it manually. 

**Insert the following code in the line around 690.** 
message ROIPoolingParameter {
  // Pad, kernel size, and stride are all given as a single value for equal
  // dimensions in height and width or as Y, X pairs.
  optional uint32 pooled_h = 1 [default = 0]; // The pooled output height
  optional uint32 pooled_w = 2 [default = 0]; // The pooled output width
  // Multiplicative spatial scale factor to translate ROI coords from their
  // input scale to the scale used when pooling
  optional float spatial_scale = 3 [default = 1];
}

**Insert the following line in the line around 320**
optional ROIPoolingParameter roi_pooling_param = 8266711;

Then build the caffe again with "make all; make pycaffe"
