### ISSUE TITLE
Planning to port PASCAL evaluation code from Matlab to Python?

### ISSUE THREAD

**Issue by yinyinl** [rbgirshick/fast-rcnn#108]
See that as one of the TODOs. Is it still planned?

**Comment by yinyinl** [comment]
Also, I don't have access to MATLAB, so tried using octave to call the evaluations. It goes to the step that finished writing the detection boxes into "comp4-<id>_det_test_<class>.txt", then gives me error:

>aeroplane: pr: load: 1862/2476
aeroplane: pr: load: 1916/2476
aeroplane: pr: load: 1971/2476
aeroplane: pr: load: 2021/2476
aeroplane: pr: load: 2076/2476
aeroplane: pr: load: 2132/2476
aeroplane: pr: load: 2191/2476
aeroplane: pr: load: 2244/2476
aeroplane: pr: load: 2293/2476
aeroplane: pr: load: 2347/2476
aeroplane: pr: load: 2403/2476
aeroplane: pr: load: 2462/2476
error: textread: could not open '/home/users/xxxxx/temp/fast-rcnn/data/VOCdevkit2007/results/VOC2007/Main/comp4-16041_det_val_aeroplane.txt' for reading
error: called from:
error:   /usr/share/octave/3.8.1/m/io/textread.m at line 82, column 5
error:   /home/users/xxxxx/temp/fast-rcnn/data/VOCdevkit2007/VOCcode/VOCevaldet.m at line 30, column 28
error:   /home/users/xxxxx/temp/fast-rcnn/lib/datasets/VOCdevkit-matlab-wrapper/voc_eval.m at line 36, column 19
error:   /home/users/xxxxx/temp/fast-rcnn/lib/datasets/VOCdevkit-matlab-wrapper/voc_eval.m at line 8, column 10

Somewhere in the eval matlab script, it wants to look for "...._val_.." instead of "...._text_...". Without too much digging myself, I am wondering if you've seen any error like this.

Thanks!

**Comment by rbgirshick** [comment]
Fixed in https://github.com/rbgirshick/py-faster-rcnn/commit/45e0da9a246fab5fd86e8c96dc351be7f145499f.

**Comment by yinyinl** [comment]
Thank you so much!
