### ISSUE TITLE
install CPU mode

### ISSUE THREAD

**Issue by fariba-abbasi** [rbgirshick/fast-rcnn#12]
Hi
can i install fast-rcnn in CPU mode? How many times CPU mode of fast-rcnn is faster than usual cnn?

**Comment by ssakhavi** [comment]
Hi

@fariba-abbasi I refer you to the following issue #9 .

**Comment by rbgirshick** [comment]
Yes, please see issue #9. A *rough* rule of thumb for running convnets on current GPUs vs CPUs: GPU will run the forward pass about 10x faster than an 8-core CPU.
