### ISSUE TITLE
Determining/changing blob dimensions

### ISSUE THREAD

**Issue by christopher-dG** [rbgirshick/fast-rcnn#122]
I'm trying to test a model on my own dataset with a model that I trained myself, this is the output:

>  Called with args:
Namespace(caffemodel='/home/degraafc/fast-rcnn/output/default/voc_2007_trainval/vgg_cnn_m_1024_fast_rcnn_iter_40000.caffemodel', cfg_file=None, comp_mode=False, gpu_id=0, imdb_name='pascal_voc', prototxt='/home/degraafc/fast-rcnn/models/VGG_CNN_M_1024/test.prototxt', set_cfgs=None, wait=True)
Using config:
{'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'default',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/degraafc/fast-rcnn',
 'TEST': {'BBOX_REG': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'BATCH_SIZE': 128,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'IMS_PER_BATCH': 2,
           'MAX_SIZE': 1000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False}}
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0524 11:28:18.265862 12501 net.cpp:42] Initializing net from parameters: 
name: "VGG_CNN_M_1024"
input: "data"
input: "rois"
state {
  phase: TEST
}
input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}
input_shape {
  dim: 1
  dim: 5
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 0
    decay_mult: 0
  }
  param {
    lr_mult: 0
    decay_mult: 0
  }
  convolution_param {
    num_output: 96
    kernel_size: 7
    stride: 2
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "norm1"
  type: "LRN"
  bottom: "conv1"
  top: "norm1"
  lrn_param {
    local_size: 5
    alpha: 0.0005
    beta: 0.75
    k: 2
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "norm1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 5
    stride: 2
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "norm2"
  type: "LRN"
  bottom: "conv2"
  top: "norm2"
  lrn_param {
    local_size: 5
    alpha: 0.0005
    beta: 0.75
    k: 2
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "norm2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "pool2"
  top: "conv3"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "conv4"
  type: "Convolution"
  bottom: "conv3"
  top: "conv4"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "conv5"
  type: "Convolution"
  bottom: "conv4"
  top: "conv5"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
  }
}
layer {
  name: "relu5"
  type: "ReLU"
  bottom: "conv5"
  top: "conv5"
}
layer {
  name: "roi_pool5"
  type: "ROIPooling"
  bottom: "conv5"
  bottom: "rois"
  top: "pool5"
  roi_pooling_param {
    pooled_h: 6
    pooled_w: 6
    spatial_scale: 0.0625
  }
}
layer {
  name: "fc6"
  type: "InnerProduct"
  bottom: "pool5"
  top: "fc6"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 4096
  }
}
layer {
  name: "relu6"
  type: "ReLU"
  bottom: "fc6"
  top: "fc6"
}
layer {
  name: "drop6"
  type: "Dropout"
  bottom: "fc6"
  top: "fc6"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "fc7"
  type: "InnerProduct"
  bottom: "fc6"
  top: "fc7"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 1024
  }
}
layer {
  name: "relu7"
  type: "ReLU"
  bottom: "fc7"
  top: "fc7"
}
layer {
  name: "drop7"
  type: "Dropout"
  bottom: "fc7"
  top: "fc7"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "cls_score"
  type: "InnerProduct"
  bottom: "fc7"
  top: "cls_score"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "bbox_pred"
  type: "InnerProduct"
  bottom: "fc7"
  top: "bbox_pred"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 8
    weight_filler {
      type: "gaussian"
      std: 0.001
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "cls_prob"
  type: "Softmax"
  bottom: "cls_score"
  top: "cls_prob"
}
I0524 11:28:18.266809 12501 net.cpp:340] Input 0 -> data
I0524 11:28:18.266825 12501 net.cpp:340] Input 1 -> rois
I0524 11:28:18.266837 12501 layer_factory.hpp:74] Creating layer conv1
I0524 11:28:18.266846 12501 net.cpp:84] Creating Layer conv1
I0524 11:28:18.266854 12501 net.cpp:380] conv1 <- data
I0524 11:28:18.266860 12501 net.cpp:338] conv1 -> conv1
I0524 11:28:18.266870 12501 net.cpp:113] Setting up conv1
I0524 11:28:18.365715 12501 net.cpp:120] Top shape: 1 96 109 109 (1140576)
I0524 11:28:18.365774 12501 layer_factory.hpp:74] Creating layer relu1
I0524 11:28:18.365787 12501 net.cpp:84] Creating Layer relu1
I0524 11:28:18.365794 12501 net.cpp:380] relu1 <- conv1
I0524 11:28:18.365803 12501 net.cpp:327] relu1 -> conv1 (in-place)
I0524 11:28:18.365813 12501 net.cpp:113] Setting up relu1
I0524 11:28:18.365874 12501 net.cpp:120] Top shape: 1 96 109 109 (1140576)
I0524 11:28:18.365895 12501 layer_factory.hpp:74] Creating layer norm1
I0524 11:28:18.365921 12501 net.cpp:84] Creating Layer norm1
I0524 11:28:18.365927 12501 net.cpp:380] norm1 <- conv1
I0524 11:28:18.365934 12501 net.cpp:338] norm1 -> norm1
I0524 11:28:18.365947 12501 net.cpp:113] Setting up norm1
I0524 11:28:18.365957 12501 net.cpp:120] Top shape: 1 96 109 109 (1140576)
I0524 11:28:18.365963 12501 layer_factory.hpp:74] Creating layer pool1
I0524 11:28:18.365984 12501 net.cpp:84] Creating Layer pool1
I0524 11:28:18.365991 12501 net.cpp:380] pool1 <- norm1
I0524 11:28:18.365998 12501 net.cpp:338] pool1 -> pool1
I0524 11:28:18.366009 12501 net.cpp:113] Setting up pool1
I0524 11:28:18.366065 12501 net.cpp:120] Top shape: 1 96 54 54 (279936)
I0524 11:28:18.366073 12501 layer_factory.hpp:74] Creating layer conv2
I0524 11:28:18.366082 12501 net.cpp:84] Creating Layer conv2
I0524 11:28:18.366101 12501 net.cpp:380] conv2 <- pool1
I0524 11:28:18.366107 12501 net.cpp:338] conv2 -> conv2
I0524 11:28:18.366130 12501 net.cpp:113] Setting up conv2
I0524 11:28:18.367213 12501 net.cpp:120] Top shape: 1 256 26 26 (173056)
I0524 11:28:18.367244 12501 layer_factory.hpp:74] Creating layer relu2
I0524 11:28:18.367264 12501 net.cpp:84] Creating Layer relu2
I0524 11:28:18.367270 12501 net.cpp:380] relu2 <- conv2
I0524 11:28:18.367279 12501 net.cpp:327] relu2 -> conv2 (in-place)
I0524 11:28:18.367286 12501 net.cpp:113] Setting up relu2
I0524 11:28:18.367434 12501 net.cpp:120] Top shape: 1 256 26 26 (173056)
I0524 11:28:18.367458 12501 layer_factory.hpp:74] Creating layer norm2
I0524 11:28:18.367466 12501 net.cpp:84] Creating Layer norm2
I0524 11:28:18.367472 12501 net.cpp:380] norm2 <- conv2
I0524 11:28:18.367480 12501 net.cpp:338] norm2 -> norm2
I0524 11:28:18.367507 12501 net.cpp:113] Setting up norm2
I0524 11:28:18.367517 12501 net.cpp:120] Top shape: 1 256 26 26 (173056)
I0524 11:28:18.367523 12501 layer_factory.hpp:74] Creating layer pool2
I0524 11:28:18.367532 12501 net.cpp:84] Creating Layer pool2
I0524 11:28:18.367538 12501 net.cpp:380] pool2 <- norm2
I0524 11:28:18.367545 12501 net.cpp:338] pool2 -> pool2
I0524 11:28:18.367553 12501 net.cpp:113] Setting up pool2
I0524 11:28:18.367607 12501 net.cpp:120] Top shape: 1 256 13 13 (43264)
I0524 11:28:18.367614 12501 layer_factory.hpp:74] Creating layer conv3
I0524 11:28:18.367636 12501 net.cpp:84] Creating Layer conv3
I0524 11:28:18.367642 12501 net.cpp:380] conv3 <- pool2
I0524 11:28:18.367665 12501 net.cpp:338] conv3 -> conv3
I0524 11:28:18.367686 12501 net.cpp:113] Setting up conv3
I0524 11:28:18.368922 12501 net.cpp:120] Top shape: 1 512 13 13 (86528)
I0524 11:28:18.368955 12501 layer_factory.hpp:74] Creating layer relu3
I0524 11:28:18.368964 12501 net.cpp:84] Creating Layer relu3
I0524 11:28:18.368971 12501 net.cpp:380] relu3 <- conv3
I0524 11:28:18.368979 12501 net.cpp:327] relu3 -> conv3 (in-place)
I0524 11:28:18.369000 12501 net.cpp:113] Setting up relu3
I0524 11:28:18.369052 12501 net.cpp:120] Top shape: 1 512 13 13 (86528)
I0524 11:28:18.369072 12501 layer_factory.hpp:74] Creating layer conv4
I0524 11:28:18.369081 12501 net.cpp:84] Creating Layer conv4
I0524 11:28:18.369101 12501 net.cpp:380] conv4 <- conv3
I0524 11:28:18.369108 12501 net.cpp:338] conv4 -> conv4
I0524 11:28:18.369117 12501 net.cpp:113] Setting up conv4
I0524 11:28:18.371726 12501 net.cpp:120] Top shape: 1 512 13 13 (86528)
I0524 11:28:18.371768 12501 layer_factory.hpp:74] Creating layer relu4
I0524 11:28:18.371791 12501 net.cpp:84] Creating Layer relu4
I0524 11:28:18.371798 12501 net.cpp:380] relu4 <- conv4
I0524 11:28:18.371808 12501 net.cpp:327] relu4 -> conv4 (in-place)
I0524 11:28:18.371816 12501 net.cpp:113] Setting up relu4
I0524 11:28:18.371897 12501 net.cpp:120] Top shape: 1 512 13 13 (86528)
I0524 11:28:18.371903 12501 layer_factory.hpp:74] Creating layer conv5
I0524 11:28:18.371914 12501 net.cpp:84] Creating Layer conv5
I0524 11:28:18.371919 12501 net.cpp:380] conv5 <- conv4
I0524 11:28:18.371927 12501 net.cpp:338] conv5 -> conv5
I0524 11:28:18.371935 12501 net.cpp:113] Setting up conv5
I0524 11:28:18.374281 12501 net.cpp:120] Top shape: 1 512 13 13 (86528)
I0524 11:28:18.374307 12501 layer_factory.hpp:74] Creating layer relu5
I0524 11:28:18.374318 12501 net.cpp:84] Creating Layer relu5
I0524 11:28:18.374325 12501 net.cpp:380] relu5 <- conv5
I0524 11:28:18.374333 12501 net.cpp:327] relu5 -> conv5 (in-place)
I0524 11:28:18.374341 12501 net.cpp:113] Setting up relu5
I0524 11:28:18.374483 12501 net.cpp:120] Top shape: 1 512 13 13 (86528)
I0524 11:28:18.374492 12501 layer_factory.hpp:74] Creating layer roi_pool5
I0524 11:28:18.374501 12501 net.cpp:84] Creating Layer roi_pool5
I0524 11:28:18.374507 12501 net.cpp:380] roi_pool5 <- conv5
I0524 11:28:18.374513 12501 net.cpp:380] roi_pool5 <- rois
I0524 11:28:18.374521 12501 net.cpp:338] roi_pool5 -> pool5
I0524 11:28:18.374529 12501 net.cpp:113] Setting up roi_pool5
I0524 11:28:18.374536 12501 roi_pooling_layer.cpp:30] Spatial scale: 0.0625
I0524 11:28:18.374552 12501 net.cpp:120] Top shape: 1 512 6 6 (18432)
I0524 11:28:18.374557 12501 layer_factory.hpp:74] Creating layer fc6
I0524 11:28:18.374565 12501 net.cpp:84] Creating Layer fc6
I0524 11:28:18.374570 12501 net.cpp:380] fc6 <- pool5
I0524 11:28:18.374578 12501 net.cpp:338] fc6 -> fc6
I0524 11:28:18.374586 12501 net.cpp:113] Setting up fc6
I0524 11:28:18.432631 12501 net.cpp:120] Top shape: 1 4096 (4096)
I0524 11:28:18.432672 12501 layer_factory.hpp:74] Creating layer relu6
I0524 11:28:18.432687 12501 net.cpp:84] Creating Layer relu6
I0524 11:28:18.432694 12501 net.cpp:380] relu6 <- fc6
I0524 11:28:18.432715 12501 net.cpp:327] relu6 -> fc6 (in-place)
I0524 11:28:18.432725 12501 net.cpp:113] Setting up relu6
I0524 11:28:18.432839 12501 net.cpp:120] Top shape: 1 4096 (4096)
I0524 11:28:18.432862 12501 layer_factory.hpp:74] Creating layer drop6
I0524 11:28:18.432870 12501 net.cpp:84] Creating Layer drop6
I0524 11:28:18.432876 12501 net.cpp:380] drop6 <- fc6
I0524 11:28:18.432883 12501 net.cpp:327] drop6 -> fc6 (in-place)
I0524 11:28:18.432893 12501 net.cpp:113] Setting up drop6
I0524 11:28:18.432916 12501 net.cpp:120] Top shape: 1 4096 (4096)
I0524 11:28:18.432924 12501 layer_factory.hpp:74] Creating layer fc7
I0524 11:28:18.432931 12501 net.cpp:84] Creating Layer fc7
I0524 11:28:18.432937 12501 net.cpp:380] fc7 <- fc6
I0524 11:28:18.432945 12501 net.cpp:338] fc7 -> fc7
I0524 11:28:18.432956 12501 net.cpp:113] Setting up fc7
I0524 11:28:18.436475 12501 net.cpp:120] Top shape: 1 1024 (1024)
I0524 11:28:18.436519 12501 layer_factory.hpp:74] Creating layer relu7
I0524 11:28:18.436544 12501 net.cpp:84] Creating Layer relu7
I0524 11:28:18.436553 12501 net.cpp:380] relu7 <- fc7
I0524 11:28:18.436560 12501 net.cpp:327] relu7 -> fc7 (in-place)
I0524 11:28:18.436570 12501 net.cpp:113] Setting up relu7
I0524 11:28:18.436663 12501 net.cpp:120] Top shape: 1 1024 (1024)
I0524 11:28:18.436686 12501 layer_factory.hpp:74] Creating layer drop7
I0524 11:28:18.436694 12501 net.cpp:84] Creating Layer drop7
I0524 11:28:18.436700 12501 net.cpp:380] drop7 <- fc7
I0524 11:28:18.436707 12501 net.cpp:327] drop7 -> fc7 (in-place)
I0524 11:28:18.436714 12501 net.cpp:113] Setting up drop7
I0524 11:28:18.436723 12501 net.cpp:120] Top shape: 1 1024 (1024)
I0524 11:28:18.436745 12501 layer_factory.hpp:74] Creating layer fc7_drop7_0_split
I0524 11:28:18.436753 12501 net.cpp:84] Creating Layer fc7_drop7_0_split
I0524 11:28:18.436759 12501 net.cpp:380] fc7_drop7_0_split <- fc7
I0524 11:28:18.436767 12501 net.cpp:338] fc7_drop7_0_split -> fc7_drop7_0_split_0
I0524 11:28:18.436779 12501 net.cpp:338] fc7_drop7_0_split -> fc7_drop7_0_split_1
I0524 11:28:18.436787 12501 net.cpp:113] Setting up fc7_drop7_0_split
I0524 11:28:18.436795 12501 net.cpp:120] Top shape: 1 1024 (1024)
I0524 11:28:18.436802 12501 net.cpp:120] Top shape: 1 1024 (1024)
I0524 11:28:18.436808 12501 layer_factory.hpp:74] Creating layer cls_score
I0524 11:28:18.436818 12501 net.cpp:84] Creating Layer cls_score
I0524 11:28:18.436825 12501 net.cpp:380] cls_score <- fc7_drop7_0_split_0
I0524 11:28:18.436832 12501 net.cpp:338] cls_score -> cls_score
I0524 11:28:18.436844 12501 net.cpp:113] Setting up cls_score
I0524 11:28:18.437347 12501 net.cpp:120] Top shape: 1 2 (2)
I0524 11:28:18.437372 12501 layer_factory.hpp:74] Creating layer bbox_pred
I0524 11:28:18.437381 12501 net.cpp:84] Creating Layer bbox_pred
I0524 11:28:18.437387 12501 net.cpp:380] bbox_pred <- fc7_drop7_0_split_1
I0524 11:28:18.437408 12501 net.cpp:338] bbox_pred -> bbox_pred
I0524 11:28:18.437417 12501 net.cpp:113] Setting up bbox_pred
I0524 11:28:18.437666 12501 net.cpp:120] Top shape: 1 8 (8)
I0524 11:28:18.437680 12501 layer_factory.hpp:74] Creating layer cls_prob
I0524 11:28:18.437703 12501 net.cpp:84] Creating Layer cls_prob
I0524 11:28:18.437710 12501 net.cpp:380] cls_prob <- cls_score
I0524 11:28:18.437716 12501 net.cpp:338] cls_prob -> cls_prob
I0524 11:28:18.437724 12501 net.cpp:113] Setting up cls_prob
I0524 11:28:18.437791 12501 net.cpp:120] Top shape: 1 2 (2)
I0524 11:28:18.437813 12501 net.cpp:169] cls_prob does not need backward computation.
I0524 11:28:18.437819 12501 net.cpp:169] bbox_pred does not need backward computation.
I0524 11:28:18.437824 12501 net.cpp:169] cls_score does not need backward computation.
I0524 11:28:18.437829 12501 net.cpp:169] fc7_drop7_0_split does not need backward computation.
I0524 11:28:18.437834 12501 net.cpp:169] drop7 does not need backward computation.
I0524 11:28:18.437854 12501 net.cpp:169] relu7 does not need backward computation.
I0524 11:28:18.437858 12501 net.cpp:169] fc7 does not need backward computation.
I0524 11:28:18.437863 12501 net.cpp:169] drop6 does not need backward computation.
I0524 11:28:18.437870 12501 net.cpp:169] relu6 does not need backward computation.
I0524 11:28:18.437875 12501 net.cpp:169] fc6 does not need backward computation.
I0524 11:28:18.437880 12501 net.cpp:169] roi_pool5 does not need backward computation.
I0524 11:28:18.437885 12501 net.cpp:169] relu5 does not need backward computation.
I0524 11:28:18.437891 12501 net.cpp:169] conv5 does not need backward computation.
I0524 11:28:18.437896 12501 net.cpp:169] relu4 does not need backward computation.
I0524 11:28:18.437914 12501 net.cpp:169] conv4 does not need backward computation.
I0524 11:28:18.437921 12501 net.cpp:169] relu3 does not need backward computation.
I0524 11:28:18.437938 12501 net.cpp:169] conv3 does not need backward computation.
I0524 11:28:18.437943 12501 net.cpp:169] pool2 does not need backward computation.
I0524 11:28:18.437948 12501 net.cpp:169] norm2 does not need backward computation.
I0524 11:28:18.437953 12501 net.cpp:169] relu2 does not need backward computation.
I0524 11:28:18.437958 12501 net.cpp:169] conv2 does not need backward computation.
I0524 11:28:18.437963 12501 net.cpp:169] pool1 does not need backward computation.
I0524 11:28:18.437969 12501 net.cpp:169] norm1 does not need backward computation.
I0524 11:28:18.437974 12501 net.cpp:169] relu1 does not need backward computation.
I0524 11:28:18.437979 12501 net.cpp:169] conv1 does not need backward computation.
I0524 11:28:18.437984 12501 net.cpp:205] This network produces output bbox_pred
I0524 11:28:18.437990 12501 net.cpp:205] This network produces output cls_prob
I0524 11:28:18.438007 12501 net.cpp:447] Collecting Learning Rate and Weight Decay.
I0524 11:28:18.438015 12501 net.cpp:217] Network initialization done.
I0524 11:28:18.438021 12501 net.cpp:218] Memory required for data: 19276464
F0524 11:28:18.985998 12501 blob.cpp:459] Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
*** Check failure stack trace: ***
Aborted (core dumped)

I've looked at caffe's [explanation of blobs](http://caffe.berkeleyvision.org/tutorial/net_layer_blob.html) but I don't really get what the last two dimensions are, are they just the height and width of the image? My input shape is supposedly: 
> input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}

so 1 image per blob, 3 feature dimensions, and I'm not really sure of the 224x224. How do I change this to be compatible?

**Comment by catsdogone** [comment]
Is the classes number in your own dataset equals 8 or you just forget to change it?
layer {
name: "bbox_pred"
...
num_output: 8
...}

**Comment by christopher-dG** [comment]
I believe it is supposed to be 4*classes, it was 84 in the original file with 21 classes.

**Comment by catsdogone** [comment]
you are right. Sorry for my carelessness.

**Comment by Jilliansea** [comment]
I have meet the same problem, could you tell me the detail about this?

**Comment by christopher-dG** [comment]
Honestly I don't really remember any of the details. Sorry I can't be of more assistance 😞
