### ISSUE TITLE
"from utils.cython_bbox import bbox_overlaps"  dynamic module does not define init function (initcython_bbox)

### ISSUE THREAD

**Issue by yytzjgsu** [rbgirshick/fast-rcnn#125]
Traceback (most recent call last):
  File "./tools/train_net.py", line 13, in <module>
    from fast_rcnn.train import get_training_roidb, train_net
  File "/home/yyt/code/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 12, in <module>
    import roi_data_layer.roidb as rdl_roidb
  File "/home/yyt/code/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 13, in <module>
    from utils.cython_bbox import bbox_overlaps
ImportError: dynamic module does not define init function (initcython_bbox)

How to solve this issue？

**Comment by dongshuyan** [comment]
i have the same question!

**Comment by marifnst** [comment]
me too
any solution for this problem ?

**Comment by albanie** [comment]
Here is a slightly hacky fix I used to get it working (so use with caution):

1. Starting in your `fast-rcnn` directory, delete the `.so` files in the subdirectories of `lib` using the `find` command:

         find lib -name "*.so" -delete
     
2. Modify [this line](https://github.com/rbgirshick/fast-rcnn/blob/master/lib/setup.py#L16) in `setup.py` from `"utils.cython_bbox"` to `"utils.bbox"`.

3. Rebuild (i.e. run `make` in the `lib` directory)
4. Change any imports that used `utils.cython_bbox` to use `utils.bbox` instead.  This can be done with the following command (again from your `fast-rcnn` directory):

        find lib -name "*.py" -exec sed -i 's/cython_bbox/bbox/g' {} +

And (Hopefully) it should now work.

**Explanation:** This kind of import error can arise when the `.pyx` filename doesn't match the extension name given in `setup.py`.

**Comment by Sharon686** [comment]
Thanks to albanie!!! My problem was solved using your method!!!

**Comment by SHEKOLDA** [comment]
@albanie this solution didn't work out for me. I was getting an ImportError: no module named cython_bbox for seemingly the same reason. After following your instructions, the error message simply changed to "no module named bbox". Do you have any ideas why could that happen? Thank you.

**Comment by ptc-meichner** [comment]
another way is to create a symlink to bbox.pyx named cython_bbox.pyx in lib/utils/ and update the setup.py entry accordingly.
no need to modify the imports then

**Comment by albanie** [comment]
@SHEKOLDA After running `make` in the third step, did you end up with a file named `bbox.so` in `lib/utils` ?

**Comment by xinyifcc** [comment]
## There is an easy way to solve this problem 
And here's the code! 

under your rcnn file     ~/rcnn/

```javascript
# install cython
sudo pip install cython scikit-image easydict
# build cython extension
make
```

### problem solved!

**Comment by aakashpatel25** [comment]
If the issue is still not fixed. Follow the steps of @albanie. Make sure bbox.so is created. Eventually instead of following step 4, comment the line that contains from utils.bbox. 

This should make the class run.

Generally what happens in Linux machine is that it tries to import bbox.so instead of the python file and hence it throws error.

**Comment by thangntt** [comment]
this issue is not fixed. I step by step follow of  @albanie.
In following step 4, I can't find cython_bbox.py file.

**Comment by Aminullah6264** [comment]
dear i have install cntk by using pip command 
pip install <url>

now when i run this FasterRCNN.py i got this error

from utils.cython_modules.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'utils.cython_modules.cython_bbox'


is there any make and build after pip installtion of CNTK

help me to solve my problem

**Comment by FrancoisPl** [comment]
@Aminullah6264 @thangntt Have you checked whether there is no other ```utils``` module in your PYTHONPATH ? It might be searching at the wrong place (which is what happened to me), you don't need the cython_bbox.py (only the cython_bbox.so) for it to work.

**Comment by Aminullah6264** [comment]
@FrancoisPl  i have solved problem.
can you tell me how can evaluate FasterRCNN for single image

**Comment by hellosaumil** [comment]
I tried adding `utils` to `PYTHONPATH`, yet the error persists.
`ModuleNotFoundError: No module named 'utils.cython_modules.cython_bbox'`
`ModuleNotFoundError: No module named 'utils.cython_modules.cpu_nms'`

Please reopen this issue.

**Comment by liya2001** [comment]
Can't believe that I fixed this bug by this answer https://stackoverflow.com/a/13976504

**Comment by hellosaumil** [comment]
@liya2001 I have a solution. [https://github.com/Microsoft/CNTK/issues/2705](https://github.com/Microsoft/CNTK/issues/2705)

**Comment by ChengweiZha** [comment]
How to fixed it?thanks a lot

**Comment by Tariq195** [comment]
I got the same issue, then I solved it using the following command. 

python -m pip install git+https://github.com/yanfengliu/cython_bbox.git
