### ISSUE TITLE
fast rcnn:when run demp.py

### ISSUE THREAD

**Issue by pubEgg** [rbgirshick/fast-rcnn#126]
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0707 17:00:06.935340  9512 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/odvs/Downloads/fast-rcnn/models/VGG16/test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

i don't konw how to fix it,any idea?

**Comment by pubEgg** [comment]
use git clone --recursive loaded,success

**Comment by sarkeribrahim** [comment]
how to solve this ?
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0718 17:01:06.813407 26562 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0718 17:01:06.813459 26562 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0718 17:01:06.813477 26562 _caffe.cpp:125] Net('/home/rvlab/Documents/fast-rcnn-master/models/VGG16/test.prototxt', 1, weights='/home/rvlab/Documents/fast-rcnn-master/data/fast_rcnn_models/vgg16_fast_rcnn_iter_40000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
F0718 17:01:06.815565 26562 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/rvlab/Documents/fast-rcnn-master/models/VGG16/test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped
