### ISSUE TITLE
ZeroDivisionError: Integer Division or Modulo by Zero

### ISSUE THREAD

**Issue by PallyPenguin** [rbgirshick/fast-rcnn#132]
Hi, when I try training my database on my own dataset, I start running into this error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()

  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)

  File "./tools/train_faster_rcnn_alt_opt.py", line 129, in train_rpn
    max_iters=max_iters)

  File ".../py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)

  File ".../py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)

  File ".../py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 144, in forward
    blobs = self._get_next_minibatch()

  File ".../py-faster-rcnn/tools/../lib/roi_data_layer/layer.py", line 63, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)

  File .../i/py-faster-rcnn/tools/../lib/roi_data_layer/minibatch.py", line 22, in get_minibatch
    assert(cfg.TRAIN.BATCH_SIZE % num_images == 0), \

ZeroDivisionError: integer division or modulo by zero

This issue was a follow up after an AssertionError with the trace-back being ` imdb.append_flipped_images----assert (boxes[:, 2] >= boxes[:, 0]).all()`
which I solved by deleting the cachefiles in $FASTER-RCNN/data/cache

I'm confused about why I am receiving the ZeroDivisionError. I traced back to the `roidb.py`, and under the `prepare_roidb(imdb)`, the correct amount of images are being put in. However, when I check the `roidb` in `minibatch.py`, I get an empty array, and the num_images is = 0.

I couldn't find any solution to this issue anywhere else.

**Comment by PallyPenguin** [comment]
Was fixed due to issue with roid_b where the params were being left empty due to issue reading annotation file of my dataset.

**Comment by daniel-merrick** [comment]
@EvanJP Hi Evan. What was wrong with your annotation file? I am having the same error but can't seem to pin down the problem.

Thank you.

**Comment by riqsebastian** [comment]
I have solved the problem by comment the 'use_diff' in the pascal_voc.py or your_database.py. If your dataset are not using difficult samples , you have to comment these lines, otherwise your dataset will be filtered to zero. It will cause your num_images become zero. FYI, If you need some ADAS dataset, please download creda open dataset on [https://www.aicreda.com/](url) Thank you.

        #if not self.config['use_diff']:
        #    # Exclude the samples labeled as difficult
        #    non_diff_objs = [
        #        obj for obj in objs if int(obj.find('difficult').text) == 0]
        #     if len(non_diff_objs) != len(objs):
        #         print 'Removed {} difficult objects'.format(
        #             len(objs) - len(non_diff_objs))
        #    objs = non_diff_objs
