### ISSUE TITLE
KeyError : Unknown dataset

### ISSUE THREAD

**Issue by baristahell** [rbgirshick/fast-rcnn#149]
Hello
I'm trying to finetune Faster RCNN using a custom dataset.
I organized my images and annotations like Pascal VOC, changed the prototxts to take the change into account.
The is, now, i have to make some changes to ``factory.py`` and ``pascal_voc.py`` so my new dataset can be found.
At the moment i added a line in the factory, let's call the dataset XXX

># Set up XXX_2017_<split>
>for year in ['2017']:
>    for split in ['test', 'test-dev']:
>        name = 'XXX_{}_{}'.format(year, split)
>        __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))

But of course it doesn't know what "XXX" actually is.

>Traceback (most recent call last):
>  File "./tools/train_net.py", line 104, in <module>
>    imdb, roidb = combined_roidb(args.imdb_name)
>  File "./tools/train_net.py", line 69, in combined_roidb
>    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
>  File "./tools/train_net.py", line 62, in get_roidb
 >   imdb = get_imdb(imdb_name)
>  File "/opt/py-faster-rcnn/tools/../lib/datasets/factory.py", line 43, in get_imdb
>    raise KeyError('Unknown dataset: {}'.format(name))
>KeyError: 'Unknown dataset: XXX'

Does anyone know what to actually change and how i have to change it, in factory.py and pascal_voc.py (and imdb.py) in order to make things run? I'm a bit lost

**Comment by indsak** [comment]
@baristahell 
how you solved this error? I am experiencing the same problem and would like to know where I missed the modification? Pls help.

**Comment by Pratosha-29** [comment]
@baristahell @indsak @rbgirshick 
Facing the same issue . kindly help.
