### ISSUE TITLE
Cannot Download pre-computed Fast R-CNN detectors

### ISSUE THREAD

**Issue by plaovem** [rbgirshick/fast-rcnn#153]
Hi,
I follow the tutorial on the github, but I cannot download the pre-computed Fast R-CNN detectors. I try to visit the website on this file. It shows that this link is invalid. Could you help me to fix it, please?

**Comment by fengsky401** [comment]
I have met the same thing. In the terminal ,it tried 20 times, showed

visionouc@visionouc-asus:~/LiuHongkun/py-faster-rcnn$ ./data/scripts/fetch_faster_rcnn_models.sh
Downloading Faster R-CNN demo models (695M)...
--2017-05-03 17:14:17--  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 45.58.69.37
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:16:25--  (try: 2)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:18:34--  (try: 3)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:20:45--  (try: 4)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... ^C
visionouc@visionouc-asus:~/LiuHongkun/py-faster-rcnn$ ./data/scripts/fetch_faster_rcnn_models.sh
File already exists. Checking md5...
Checksum is incorrect. Need to download again.
Downloading Faster R-CNN demo models (695M)...
--2017-05-03 17:22:54--  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 45.58.69.37
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:25:02--  (try: 2)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:27:11--  (try: 3)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:29:22--  (try: 4)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:31:33--  (try: 5)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:33:45--  (try: 6)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:35:58--  (try: 7)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:38:13--  (try: 8)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:40:28--  (try: 9)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:42:44--  (try:10)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:45:01--  (try:11)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:47:19--  (try:12)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:49:36--  (try:13)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:51:53--  (try:14)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:54:10--  (try:15)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:56:28--  (try:16)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 17:58:45--  (try:17)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 18:01:02--  (try:18)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 18:03:19--  (try:19)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Retrying.

--2017-05-03 18:05:36--  (try:20)  https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.69.37|:443... failed: Connection timed out.
Giving up.

Unzipping...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Done. Please run this comma

**Comment by ihciah** [comment]
Dropbox is blocked in some countries. Try to use a proxy. `proxychains` is a good choice.

**Comment by squirrel233** [comment]
@ihciah How to use it?
I've tried:
```
me:~/fast-rcnn$ proxychains ./data/scripts/fetch_fast_rcnn_models.sh

ProxyChains-3.1 (http://proxychains.sf.net)
File already exists. Checking md5...
Checksum is incorrect. Need to download again.
Downloading Fast R-CNN demo models (0.96G)...
--2017-07-12 17:34:04--  https://dl.dropboxusercontent.com/s/e3ugqq3lca4z8q6/fast_rcnn_models.tgz
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... |DNS-request| dl.dropboxusercontent.com 
|S-chain|-<>-127.0.0.1:9050-<--timeout
|DNS-response|: dl.dropboxusercontent.com does not exist
failed: Unknown error.
wget: unable to resolve host address ‘dl.dropboxusercontent.com’
Unzipping...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Done. Please run this command again to verify that checksum = 5f7dde9f5376e18c8e065338cc5df3f7.
```
Maybe I made a mistake when using proxychains, plz note it, thanks!

**Comment by ihciah** [comment]
@squirrel233 In China Dropbox is blocked. Just setup a proxy server like shadowsocks(or buy one), and then run a client to create a socks5 proxy. Change proxychains' setting and point it to your socks5 ip and port. Then the proxychains should work well.

**Comment by squirrel233** [comment]
@ihciah thanks~

**Comment by tranquoclongt1** [comment]
@squirrel233 have you downloaded models? Could you mind shared them on google drive or some online storage? I used proxychains but still have the similar problem
```
proxychains ./data/scripts/fetch_faster_rcnn_models.sh 
ProxyChains-3.1 (http://proxychains.sf.net)
File already exists. Checking md5...
Checksum is incorrect. Need to download again.
Downloading Faster R-CNN demo models (695M)...
--2018-05-05 03:23:02--  http://www.cs.berkeley.edu/~rbg/faster-rcnn-data/faster_rcnn_models.tgz
Resolving www.cs.berkeley.edu (www.cs.berkeley.edu)... |DNS-request| www.cs.berkeley.edu 
|S-chain|-<>-127.0.0.1:1280-<--timeout
|DNS-response|: www.cs.berkeley.edu does not exist
failed: Unknown error.
wget: unable to resolve host address ‘www.cs.berkeley.edu’
Unzipping...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Done. Please run this command again to verify that checksum = ac116844f66aefe29587214272054668.
```

**Comment by WenjieDuan** [comment]
yes, I have this problem as well.
maybe u can download it directly from the website, like " https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0". I have used this method, it works!

**Comment by liceHuang** [comment]
> yes, I have this problem as well.
> maybe u can download it directly from the website, like " https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0". I have used this method, it works!

well ! this works!! thk vm!
