### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by XavierFrazao** [rbgirshick/fast-rcnn#17]
Hi all.
I hope you can help me.
I get the following error during make.

...
...
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/image_data_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/syncedmem.cpp
NVCC src/caffe/util/math_functions.cu
NVCC src/caffe/util/im2col.cu
NVCC src/caffe/layers/prelu_layer.cu
NVCC src/caffe/layers/relu_layer.cu
src/caffe/layers/prelu_layer.cu(58): error: a host function call cannot be configured
          detected during instantiation of "void caffe::PReLULayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(127): here

src/caffe/layers/prelu_layer.cu(92): error: a host function call cannot be configured
          detected during instantiation of "void caffe::PReLULayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(127): here

src/caffe/layers/prelu_layer.cu(118): error: a host function call cannot be configured
          detected during instantiation of "void caffe::PReLULayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(127): here

src/caffe/layers/prelu_layer.cu(58): error: a host function call cannot be configured
          detected during instantiation of "void caffe::PReLULayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(127): here

src/caffe/layers/prelu_layer.cu(92): error: a host function call cannot be configured
          detected during instantiation of "void caffe::PReLULayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(127): here

src/caffe/layers/prelu_layer.cu(118): error: a host function call cannot be configured
          detected during instantiation of "void caffe::PReLULayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(127): here

6 errors detected in the compilation of "/tmp/tmpxft_000008af_00000000-16_prelu_layer.compute_50.cpp1.ii".
make: *** [.build_release/cuda/src/caffe/layers/prelu_layer.o] Error 1
make: *** Waiting for unfinished jobs....
src/caffe/layers/relu_layer.cu(25): error: a host function call cannot be configured
          detected during instantiation of "void caffe::ReLULayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(62): here

src/caffe/layers/relu_layer.cu(55): error: a host function call cannot be configured
          detected during instantiation of "void caffe::ReLULayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(62): here

src/caffe/layers/relu_layer.cu(25): error: a host function call cannot be configured
          detected during instantiation of "void caffe::ReLULayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(62): here

src/caffe/layers/relu_layer.cu(55): error: a host function call cannot be configured
          detected during instantiation of "void caffe::ReLULayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(62): here

4 errors detected in the compilation of "/tmp/tmpxft_000008e4_00000000-16_relu_layer.compute_50.cpp1.ii".
make: *** [.build_release/cuda/src/caffe/layers/relu_layer.o] Error 1

...

I already try to solve it but i fail. 
I get the same error with different versions of cuda. (i'm using 7-0 by default).

Ps. With the original version of caffe everything works.

Thanks

**Comment by rbgirshick** [comment]
My recommendation is to look for help in the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
