### ISSUE TITLE
Out of memory while running demo.py

### ISSUE THREAD

**Issue by markotitel** [rbgirshick/fast-rcnn#2]
Hello,

I have found several similar issues with out of memory problem regarding caffe.
I am not sure if my issue is connected to caffe or fast-rcnn tuning.
I have amazon instance, nvidia-smi gives:
```
+------------------------------------------------------+                       
| NVIDIA-SMI 340.29     Driver Version: 340.29         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   36C    P0    43W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GRID K520           Off  | 0000:00:04.0     Off |                  N/A |
| N/A   30C    P0    41W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GRID K520           Off  | 0000:00:05.0     Off |                  N/A |
| N/A   38C    P0    44W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GRID K520           Off  | 0000:00:06.0     Off |                  N/A |
| N/A   34C    P0    36W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|  No running compute processes found                                         |
+-----------------------------------------------------------------------------+
```

Actual error output I get is:
```
I0502 15:34:45.246454 36085 net.cpp:218] Memory required for data: 114633208
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 538766130


Loaded network data/fast_rcnn_models/vgg16_fast_rcnn_iter_40000.caffemodel

Demo for data/demo/000004.jpg
F0502 15:34:46.777649 36085 syncedmem.cpp:57] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
```

I have found that I have to reduce batch size. I cannot get it in which file to decrease and if that is the only thing neede. O r I have to recompile something afterwards.

Kindly thanks

**Comment by rbgirshick** [comment]
Unfortunately you won't be able to use VGG16 with these GPUs, they just don't have enough memory. Even if you go down to using a single image per batch (controlled in lib/fast_rcnn/config.py, btw), you'll still need ~5G of memory.

You'll be able to train VGG_CNN_M_1024 and CaffeNet on these cards.

**Comment by markotitel** [comment]
Thank you for helping.

**Comment by forresti** [comment]
If we reduce BATCH_SIZE in config.py, could that enable fast-rcnn to run on low-memory GPUs? (I played with this a bit and it still ran out of memory... but I haven't investigated deeply yet.)

**Comment by markotitel** [comment]
@forresti Interesting that after installing CUDNN I got no memory trouble.

**Comment by bipul21** [comment]
I am facing the same problem AWS g2.2xlarge when running demo.py

Should it work there? Or any option ?

**Comment by sid027** [comment]
Could anyone solve this issue yet?I reduced the BATCH_SIZE from 128 to 16 in the config.py file.Still running out of memory!

**Comment by bipul21** [comment]
Edit the same. Try the caffenet model.

By running ./tools/demo.py --net=caffenet

On Sun, Oct 18, 2015 at 10:56 PM, Sid <notifications@github.com> wrote:

> Could anyone solve this issue yet?I reduced the BATCH_SIZE from 128 to 16
> in the config.py file.Still running out of memory!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rbgirshick/fast-rcnn/issues/2#issuecomment-149031925>.
>



-- 
Regards
Bipul Jain
+91-9845885679

**Comment by aaronpolhamus** [comment]
@bipul21: what't the process for passing caffenet into the demo as a valid option? currently executing your command results in `demo.py: error: argument --net: invalid choice: 'caffenet' (choose from 'vgg16', 'zf')`

**Comment by aaronpolhamus** [comment]
ah, my mistake, i'm using faster-py-rcnn and was referencing the issues page for fast-rcnn. any guidance for troubleshooting this issue with py-faster-rcnn?

**Comment by erohan** [comment]
@markotitel  Although i installed CudNN5 from https://developer.nvidia.com/rdp/cudnn-download and copied header files to include and shared so libraries to lib64 memory problem continued.

I am trying to run demo of Fast R-CNN on Ubuntu 14.04. Lastly i run it through ./demo.py --net=zf and it gave an output of detected person, cat, dog, horse, bus.. etc. So, VGG16 database is big and i think everybody must start wt. a small sample. Currently my solution is this for Fast R-CNN

**Comment by markotitel** [comment]
@erohan Hi, unfortunately I am a mere copy paster and google search user. It was more than a year now, I cant help no further on this. But I would advise to start from scratch and follow every step fully.

I may have somewhere Ansible script for setting up the instance though. But don't think it will help a lot hence in a year period guess a lot has changed.

**Comment by erohan** [comment]
@markotitel Lastly I installed nVidia CUDA drivers and because of 2048 MB memory of my graphic card, the VGG16 does not run; it needs approximately 5 GB.

So, i run VGG16 with --cpu option to see @ demo phase. --cpu realy performs very slower whan you compare it wt. default option (GPU) but i can try some work so no need to investigate much more about this memory problem.

Thanks again for your answer. Regards.

**Comment by Vandertic** [comment]
I found a solution somewhere else and it worked for me.

You have to use CUDNN libraries, but **not** the most recent ones (presently 5.1) the caffe branch inside py-faster-rcnn/caffe-faster-rcnn, only supports **cudnn 4**.
Libraries cudnn 4 were originally developed for cuda 7.0 but they work without problems on cuda 8.0 and ubuntu 16.04. With those installed, after compiling caffe (with USE_CUDNN:=1 in the Makefile.config), everything worked fine. The demo.py completed successfully on a 2Gb GeForce GTX 950.
