### ISSUE TITLE
Selective Search Configuration

### ISSUE THREAD

**Issue by shicai** [rbgirshick/fast-rcnn#26]
Hi Ross,

 I run your demo, and it works good.
But when I use your selective search matlab code from your rcnn repo to generate object proposals for image 000001.jpg, I can only get 2393 proposals, which is not the same as your mat file (2880 proposals). By using these proposals, only 2 cars are detected.
So would you please tell me your configurations of selective search methods?
Or How can I get 2880 proposals for image 000001.jpg?
Thanks.

**Comment by ouxinyu** [comment]
I change the boxsize and sigma, the proposals is change, but the result is worse than 2880 proposals for image 000004.jpg

**Comment by rbgirshick** [comment]
For that particular image, I used the pre-computed selective search boxes from http://homepages.inf.ed.ac.uk/juijling/index.php#page=projects1. The authors say they used "fast mode", but perhaps they computed those boxes with a slightly different version of selective search than what they released?

For datasets after VOC 2007, I used the code here: https://github.com/rbgirshick/rcnn/tree/master/selective_search to compute boxes myself. Those should be reproducible. It's unfortunate that the boxes they distributed for 2007 seem hard to reproduce (all the more reason to move beyond selective search: http://arxiv.org/abs/1506.01497).

**Comment by GeorgiAngelov** [comment]
@rbgirshick, Do you know when the code will be released for the methods proposed in the paper you referred to? I am looking forward to this new setup of RPN + Fast-RCNN !

P.S. A big THANK YOU for fast-rcnn and all of your hard work!

**Comment by deartonym** [comment]
I should read this issue earlier. I found the same problem, that their result for the 2880 proposals can hardly be reproduced (I tried many different parameters). I think we should not spend more time on this issue, and we can try other proposal methods as well.

**Comment by yao5461** [comment]
@shicai, I also met the same problem. Maybe you can try this way(matlab):
1> Generate object proposals for the image, such as: `boxes_tmp = selective_search_boxes(im)`;
     the selective search matlab code: https://github.com/rbgirshick/rcnn/blob/master/selective_search
2> Change the format: `boxes = boxes_tmp(:, [2 1 4 3]) - 1`;
3> Save the boxes into a mat file and test it.
I think more cars will be detected. 

From the source code, I found:
a. The format of proposals in demo mat file is: `[left, top, right, bottom], 0-based index`.
    Line 86-86: https://github.com/rbgirshick/fast-rcnn/blob/master/lib/fast_rcnn/test.py
b. The format of proposals produced by matlab code is: `[top, left, bottom, right], 1-based index`.
    Line 145: https://github.com/rbgirshick/fast-rcnn/blob/master/lib/datasets/pascal_voc.py

The code for training changes the format of proposals to `[left, top, right, bottom], 0-based index`, but the test code doesn't. I guess it is the reason. Hope these will be helpful.

**Comment by shicai** [comment]
thanks @rbgirshick for your great job.
btw, when will you release the faster rcnn code?
we are looking forward to trying it:)

thanks @yao5461, it's very helpful.
row major vs column major, and 0-based index vs 1-based major
that's the difference between python/c++ and matlab.

**Comment by MinaRe** [comment]
Hi Guys
I have received this problem when I want to run demo ,I dont have any idea ,can you please help me.
Thanks in advance!


OptiPlex-990:~/selective_search_py$ ./demo_showcandidates.py --image image.jpg
Traceback (most recent call last):
  File "./demo_showcandidates.py", line 12, in <module>
    import selective_search
  File "/home/minarezaei/selective_search_py/selective_search.py", line 10, in <module>
    import segment
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py34.so.1.54.0: undefined symbol: PyUnicode_AsUTF8String

**Comment by 345ishaan** [comment]
Hi Mina,

Did your issue got resolved?

**Comment by tengerye** [comment]
> Hi Ross,
> 
> I run your demo, and it works good.
> But when I use your selective search matlab code from your rcnn repo to generate object proposals for image 000001.jpg, I can only get 2393 proposals, which is not the same as your mat file (2880 proposals). By using these proposals, only 2 cars are detected.
> So would you please tell me your configurations of selective search methods?
> Or How can I get 2880 proposals for image 000001.jpg?
> Thanks.

Where is the image 000001.jpg? @shicai 

As to the image 000004.jpg, the matlab file proposes 2383 rectangles while the given one in the repository is 2888.
