### ISSUE TITLE
demo.py only supports 20 classes?

### ISSUE THREAD

**Issue by mdering** [rbgirshick/fast-rcnn#27]
I'm trying to use the hybridCNN model from the zoo with a modified version of the demo code and for some reason the scores only return up to 20 classes. Is there a reason for this? I can't find anywhere in the code that says why this might be.

**Comment by prsarv** [comment]
@mdering I noticed that you closed this issue. I was wondering if you figured out why this is happening? Any help would be appreciated. Thanks.

**Comment by mdering** [comment]
The models this software ships with have their final layer trained on the 20 +1 classes of the VOC challenge, if you wish to get different classes you must retrain it. I think thats the issue

**Comment by prsarv** [comment]
Drat. I wished this was not the situation but I too arrived at the same conclusion. I guess this means that the pre-trained Imagenet models with fast-rcnn are only trained over pascal voc object classes. Not all 200 Imagenet classes.

Thanks for your response! Much Appreciated.

**Comment by mdering** [comment]
I managed to get them trained on the 200 DET classes eventually, i will post some code in the coming weeks that helped me do it.

**Comment by mdering** [comment]
in the meantime, this group seems to have the right idea, though they're training on the INRIA dataset https://github.com/EdisonResearch/fast-rcnn

**Comment by prsarv** [comment]
Cheers. I will take a look.

**Comment by liuchang8am** [comment]
Hi, @mdering ,  I'm trying to train on 200 DET too, did you re-organize the images and the annotations for 200 DET in the way that https://github.com/EdisonResearch/fast-rcnn mentioned?  That is, to copy all the images into one "image" folder and all the annotations in one "annotation" folder?Thanks.

**Comment by mdering** [comment]
Thats a good question, basically no.
The short answer is that file index just needs to contain file names, so having a row like n03636649/n03636649_8522 will look for a file called n03636649_8522.JPEG in a folder called n03636649 under the images folder with minimal tweaking. That's perfectly fine. I'm going to try to get a fork up this week with at least my imagenet.py, which can do training, but doesn't do validation or testing just yet.

The only other thing you need to be aware of is that not all of the images in the training files actually contain an annotated box, which is a problem. also one of the annotations is incorrect, in that its xmin is greater than its xmax.

**Comment by sunshineatnoon** [comment]
@mdering Did you finished getting a fork up? I want to try training on the imagenet 200 Detection Dataset too, where should I look first? Thanks.

**Comment by IdiosyncraticDragon** [comment]
@mdering hello, I am tring to train the fast rcnn on 200 DET these days, too. But I met a problem while generating the proposals for the 200 DET, it looks like some of the images in the ImageNet dataset are gray images,  and it cost the rgb2hsv function (This function is called by selective search)  to be failed. So I'm wondering did you do some converting before generating proposals by selective search? Thanks.
