### ISSUE TITLE
a Error in VOCevaldet(line 30)

### ISSUE THREAD

**Issue by ouxinyu** [rbgirshick/fast-rcnn#28]
I am very like this project. I finish the demo.py and train.py, but when I excute the command “./tool/test_net.py....” ， I meet a error after extract features.
very hope to be able to get helps.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~``
aeroplane: pr: load: 3795/4952
aeroplane: pr: load: 4013/4952
aeroplane: pr: load: 4237/4952
aeroplane: pr: load: 4462/4952
aeroplane: pr: load: 4690/4952
aeroplane: pr: load: 4899/4952
Error using textread (line 165)
File not found.

Error in VOCevaldet (line 30)
[ids,confidence,b1,b2,b3,b4]=textread(sprintf(VOCopts.detrespath,id,cls),'%s %f
%f %f %f %f');


Error in voc_eval>voc_eval_cls (line 36)
  [recall, prec, ap] = VOCevaldet(VOCopts, comp_id, cls, true);

Error in voc_eval (line 8)
  res(i) = voc_eval_cls(cls, VOCopts, comp_id, output_dir, rm_res);
 
165     error(message('MATLAB:textread:FileNotFound'));

**Comment by shicai** [comment]
seems that your matlab functions could not been found.
check your matlab functions, which should be included in the MATLAB path.

**Comment by ouxinyu** [comment]
@shicai I checked my files and followed the introduction to set all my files. train_net.py,compress.py, demo.py is well down. So I don;t konow how to fixed it

**Comment by ouxinyu** [comment]
sorry, I forgotten change the VOC dataset initialize. I close this comment.

**Comment by pmuyan** [comment]
I am having the same problem. Could you please give me more information on how to "change the VOC dataset initialize"?

**Comment by vvkdby** [comment]
In VOCCode, inside the VOCdevkit folder, there will be a file called VOCinit. 
In that, on around line 31, change the VOC.testset to 'test' instead of 'val'

**Comment by leejiajun** [comment]
@ouxinyu I am also in this trouble. How to change the VOC dataset initialize? 
Thank you.
