### ISSUE TITLE
Utilizing CuDNN

### ISSUE THREAD

**Issue by ssakhavi** [rbgirshick/fast-rcnn#3]
Hi, 

I had a question: by default I was trying to use CuDNN to `make` your caffe fork. But after seeing your `Makefile.Config`, I noticed you don't use CuDNN.

Why is that? Wouldn't that accelerate the code more?

**Comment by rbgirshick** [comment]
Things may have changed, but last I tried cuDNN was slower than Caffe's default conv engine for VGG16. Fiddling with the conv engine may speed up other models, though. Feel free to play around and let us know what you find.

**Comment by ssakhavi** [comment]
OK.

Thanks.
