### ISSUE TITLE
About DEDUP_BOXES and spatial_scale 

### ISSUE THREAD

**Issue by siki5068** [rbgirshick/fast-rcnn#34]
Hi rbgirshick, 

First, thanks for sharing fast rcnn code. 

I have a question about DEDUP_BOXES and spatial_scale. I don't understand why they are set to 1/16 (= 0.0625). I can't find any relevant explanation in your paper. Can you please explain such setting? thank you.

**Comment by rbgirshick** [comment]
1/16 comes from the fact that the network performs a 16x spatial reduction through max pooling or strided convolution.
