### ISSUE TITLE
Multiple tops for input blob

### ISSUE THREAD

**Issue by riddhiman-dasgupta** [rbgirshick/fast-rcnn#4]
Hi,
This might not be the best place for asking this question, so apologies in advance.
In all the network definitions, for the training phase, in the models folder, the data layer seems to be of the following format:
  ```
layer {
  name: 'data'
  type: 'Python'
  top: 'data'
  top: 'rois'
  top: 'labels'
  top: 'bbox_targets'
  top: 'bbox_loss_weights'
  python_param {
    module: 'roi_data_layer.layer'
    layer: 'RoIDataLayer'
    param_str: "'num_classes': 21"
  }
}
```
Are data layers with multiple top blobs(corresponding to multiple labels in this case) a part of Caffe right now, or are they incorporated here using the ```roi_data_layer``` python layer that is present in the lib folder?
I wanted to train a network on multiple tasks(similar to the classification and bounding box regression that are jointly learnt in ```Fast-RCNN```), and hence was wondering what would be the best way to have a data layer that outputs multiple tops, one for each type of label.

**Comment by rbgirshick** [comment]
Hi @riddhiman-dasgupta, the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) google group is the best place for this type of question. An existing data layer may fit your needs. If not, a simple and flexible option is to write a Python layer (you can model it after the roi_data_layer).
