### ISSUE TITLE
NMS performance

### ISSUE THREAD

**Issue by only4hj** [rbgirshick/fast-rcnn#40]
Hi,
When I run demo.py, NMS(Non-maximum suppression) takes quite amount of time.

I ran demo.py with all the 20 classes in my PC (i5 CPU, GTX970)
which means nms runs 20 times per image.

And the result shows that nms takes big portion of time in the overall detection process.

[ 000004.jpg ]
im_detect : 0.44s
total nms : 0.39s

[ 001551.jpg ]
im_detect : 0.34s
total nms : 0.17s

This nms time will increase as the number of the detection classes increases.
Even though the current Cython implementation of nms reduces elapsed time,
it will be very helpful if there is much faster implementations of nms.

Any suggestion of faster implementations of nms?

**Comment by rbgirshick** [comment]
You should only apply NMS to detections that have a score greater than some threshold. For example, even a low threshold of 0.05 greatly reduces the number of detections to process, and thus speeds up the NMS calls. For the demo, I've updated it to use the conf threshold that's already in the code.

**Comment by only4hj** [comment]
Thanks!!

**Comment by tharuniitk** [comment]
Hello @only4hj @rbgirshick 
How to tune NMS_threshold, Conf_threshold when we test faster rcnn on custom dataset. Grateful for  your valuable insights
