### ISSUE TITLE
selective search parameters for generating the .mat files 

### ISSUE THREAD

**Issue by pmuyan** [rbgirshick/fast-rcnn#41]
I am trying to re-generate the .mat files used in the demo (e.g. 000004_boxes.mat).

I have downloaded the selective search IJCV code and used fast-mode to generate boxes for 000004.jpg.

I have saved the generated boxes in a .mat file. However, I see that default parameters of IJCV code does not generate the same boxes as  000004_boxes.mat has. 

I have disabled the fast code and re-generate the .mat file. But still generated boxes are not the same (file sizes are different and result of the demo shows that only two cars can be detected in 000004.jpg).

So I was wondering what is the correct selective search parameters for generating 000004_boxes.mat.

Thanks!

**Comment by wanghao2020** [comment]
@pmuyan  Hello, I have the same problem with you . i try the selective search IJCV code and achieve author's  rcnn/selective_search/selective_search_boxes.m code .i also can't get the same result. i was wondering for a lot of time . 
can anyone solve it ?

**Comment by rbgirshick** [comment]
The boxes for the demo image come from the VOC 2007 download on Jasper Uijling's homepage: http://homepages.inf.ed.ac.uk/juijling/index.php#page=projects1. My understanding is that these boxes were generated with a deprecated version of selective search, not the IJCV version.

**Comment by ZiangYan** [comment]
The boxes for the demo are not generated from selective search IJCV code. I use IJCV version to re-generate .mat files and run fast-cnn using CaffeNet again, finally get 57.0 mAP (57.1 in fast-rcnn 2015 ICCV paper).
