### ISSUE TITLE
PASCAL VOC 2007 Dataset (x-post)

### ISSUE THREAD

**Issue by bluemellophone** [rbgirshick/fast-rcnn#5]
I've been trying to get this implementation online, but am running into a roadblock with the PASCAL 2007 dataset. It appears as though pascallin.ecs.soton.ac.uk is down and unreachable.

Does anybody have a working mirror or willing to host a copy of the data:

* http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
* http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2007/VOCtest_06-Nov-2007.tar
* http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2007/VOCdevkit_08-Jun-2007.tar

If I can get a copy of the data, I will add it to the academictorrents.com tracker so this doesn't happen again.

Edit: I'm still trying to track them all down, but I've added some of the missing VOC dataset files to academictorrents.com: http://academictorrents.com/browse.php?search=voc

*Note: this is a repost from https://github.com/rbgirshick/rcnn/issues/48, for visibility.*

**Comment by XericZephyr** [comment]
I got first two files from baidu cloud, a famous Chinese cloud storage service. However, I cannot get the last devkit which sizes only 250 kb.  

I don't know whether it's legal to redistribute the dataset. So I guess you can do some google search towards baidu cloud to get the dataset (though without the devkit).

**Comment by laotao** [comment]
https://web.archive.org/web/20140815141459/http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2012/index.html

**Comment by wangdelp** [comment]
CyrusChiu found one on oxford website, tested work for me. 

wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCdevkit_08-Jun-2007.tar
