### ISSUE TITLE
Training Problem on MS COCO

### ISSUE THREAD

**Issue by twtygqyy** [rbgirshick/fast-rcnn#54]
I would like to train a fast-rcnn model on MS COCO dataset according to the COCO branch.
I have generate selective search proposals and the coco.py could load all 82783 mat files successfully.
However, the code stops with the error of roidb = datasets.imdb.merge_roidbs(gt_roidb, method_roidb)
*** ValueError: blocks[0,:] is all None

How can I solve this problem? I appreciate it if someone could help.

**Comment by markusnagel** [comment]
I had the same issue. Further investigations showed that the error comes at 'image 29'. This image has 0 gt annotations. Somehow it seems that scipy.sparse.vstack have a bug with concatenating sparse arrays that have a dimension with 0 length. You can manually handle that case in imdb.py by changing line 224 to:
if np.shape(a[i]['gt_overlaps'])[0] > 0:
    a[i]['gt_overlaps'] = scipy.sparse.vstack([a[i]['gt_overlaps'],
                                                       	            b[i]['gt_overlaps']])
else:
    a[i]['gt_overlaps'] = b[i]['gt_overlaps']

**Comment by rbgirshick** [comment]
I haven't run into this issue with scipy 0.15.1 (via the anaconda distro).

**Comment by twtygqyy** [comment]
Can you show the mAP of fast rcnn on MS COCO dataset?

**Comment by markusnagel** [comment]
I got a mAP of .196 on the validation set with fast rcnn using edge boxes 70 as proposals and the VGG16.  This is very similar what Ross have on the leader-board of the test-dev set. With using the VGG M net the mAP drops to .155 for me.
Here are all scores (see coco evaluation for their definition)
vgg_cnn_m_1024_fast_rcnn_iter_280000.caffemodel	0.155	0.315	0.138	0.023	0.150	0.270	0.179	0.260	0.266	0.059	0.292	0.445
vgg16_fast_rcnn_iter_240000.caffemodel	0.196	0.375	0.186	0.034	0.204	0.332	0.209	0.302	0.308	0.079	0.352	0.505

**Comment by twtygqyy** [comment]
@markusnagel Thanks a lot for your help. The problem solved after modifying imdb.py as you mentioned.
I think we could close this issue.
