### ISSUE TITLE
Did Any try LPO to generate proposals?

### ISSUE THREAD

**Issue by mbahacker** [rbgirshick/fast-rcnn#56]
I am trying to use .hf5 files generated by lpo's selective search proposal. 
I want to modify demo.py and use my *.hf5 box files instead of *.mat. Anyone tried that before?

**Comment by mbahacker** [comment]
Closing the issue as I figured out the solution by myself. It's just how the arrays are stored hierarchically

**Comment by IdiosyncraticDragon** [comment]
What's your exact solution? I met this problem, too. And I have no idea with it.
Thank you!

**Comment by mbahacker** [comment]
Here is the sample code I used. Let me know if you need further help:

with h5py.File('/home/.hf5','r') as hf:
        print('List of arrays in this file: \n', hf.keys())
        data = hf.get('box_0')
        obj_proposals = np.array(data)
        for i in range(1,(len(hf.keys())-1)):
            keyName='box_'+str(i)
            keyData=hf.get(keyName)
            obj_proposals=np.concatenate((obj_proposals,np.array(keyData)),axis=0)

**Comment by IdiosyncraticDragon** [comment]
Thanks very much!
