### ISSUE TITLE
nms error

### ISSUE THREAD

**Issue by sxjzwq** [rbgirshick/fast-rcnn#57]
in some case, I got an error of using mns
following codes are from demo

dets = np.hstack((cls_boxes,cls_scores[:, np.newaxis])).astype(np.float32)
keep = nms(dets, NMS_THRESH)
dets = dets[keep, :]

It gave me error as following
Traceback (most recent call last):

  File "<ipython-input-23-b9ee32d7adbb>", line 7, in <module>
    keep = nms(dets, NMS_THRESH)

  File "nn/lib/utils/nms.pyx", line 64, in utils.cython_nms.nms (utils/nms.c:2134)

ZeroDivisionError: float division

**Comment by ShawnXUNJU** [comment]
Hi, I got the same error.
Could you share your solutions? Thanks.

**Comment by sxjzwq** [comment]
It is the problem of proposal bounding box.
You should check whether your proposal bounding box's width and height bigger than 0. MCG sometimes return a non-valued bounding box. Selective search has no such problem.

Anyway, check your bounding box at first.

**Comment by ShawnXUNJU** [comment]
Thanks for your quick reply and good suggestion.

It is weird because the bounding box is generated by selective search in my experiments.

**Comment by ShawnXUNJU** [comment]
Thank for your hints @sxjzwq .

I think the bounding-boxes returned from the bounding-box regresser may not follow the "well-known" convention. In other words, the area of returned bounding-box may be 0 or negative. @rbgirshick

**Comment by sxjzwq** [comment]
Yes. And if the area of the bounding-box is zero, there will be more problems in the training.

In fast-rcnn/lib/roi_data_layer/roidb.py, line114-line115, 
    targets_dx = (gt_ctr_x - ex_ctr_x) / ex_widths
    targets_dy = (gt_ctr_y - ex_ctr_y) / ex_heights
if the ex_weight == 0, the bounding-box regression targets will be a extremely large number.
I simply remove those  zero area bounding boxes before this step,
