### ISSUE TITLE
selective search coordinates

### ISSUE THREAD

**Issue by lolongcovas** [rbgirshick/fast-rcnn#59]
after downloading the precomputed boxes by selective search via fetch_selective_search_data.sh, I wonder whether the coordinates are [x, y, w, h], [x1,y1,x2,y2], [y, x, h, w] or other combination.

Best

**Comment by awayhome113** [comment]
It should be [x1,y1,x2,y2], meaning [left, top, right, bottom].

**Comment by lolongcovas** [comment]
Thanks

**Comment by zhaohui-yang** [comment]
I wonder why in roidb_from_voc.m file, there is a line:
% change selective search order from [y1 x1 y2 x2] to [x1 y1 x2 y2]
boxes = boxes(:, [2 1 4 3]);

are boxes really [x1, y1, x2, y2]?

**Comment by zhaohui-yang** [comment]
I have checked the program that the original selective search data is organized by [y1, x1, y2, x2].
