### ISSUE TITLE
Error while running 'make runtest' for the caffe of fast-rcnn

### ISSUE THREAD

**Issue by AmNotGod** [rbgirshick/fast-rcnn#6]
I really appreciate  that the research helps to improve the performance of original rcnn greatly. However, there is something wrong when I try to compile the caffe of the fast-rcnn. Errors occur while running "make runtest".
----------------------------------------
[----------] 1 test from ROIPoolingLayerTest/0, where TypeParam = caffe::FloatCPU
[ RUN      ] ROIPoolingLayerTest/0.TestGradient
F0505 10:07:28.363382 28868 roi_pooling_layer.cpp:130] Not Implemented Yet
*** Check failure stack trace: ***
    @     0x2b5e374c8daa  (unknown)
    @     0x2b5e374c8ce4  (unknown)
    @     0x2b5e374c86e6  (unknown)
    @     0x2b5e374cb687  (unknown)
    @     0x2b5e38e8201c  caffe::ROIPoolingLayer<>::Backward_cpu()
    @           0x4b86d4  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x4b9649  caffe::GradientChecker<>::CheckGradientExhaustive()
    @           0x4fd21b  caffe::ROIPoolingLayerTest_TestGradient_Test<>::TestBody()
    @           0x73201d  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x729fb1  testing::Test::Run()
    @           0x72a096  testing::TestInfo::Run()
    @           0x72a1d7  testing::TestCase::Run()
    @           0x72a52e  testing::internal::UnitTestImpl::RunAllTests()
    @           0x731b9d  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x72960e  testing::UnitTest::Run()
    @           0x443b82  main
    @     0x2b5e39ad9ec5  (unknown)
    @           0x448b64  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] 已放弃 (core dumped)
----------------------------------
I can't figure it out. Any help will be appreciated!

**Comment by ltl315** [comment]
Hi, I encounter the same problem when I tried to make runtest. Hope someone give some tips to solve it.
[----------] 1 test from ROIPoolingLayerTest/1, where TypeParam = caffe::DoubleCPU
[ RUN      ] ROIPoolingLayerTest/1.TestGradient
F0505 11:12:48.980974  8613 roi_pooling_layer.cpp:130] Not Implemented Yet
*** Check failure stack trace: ***
    @     0x2b699bb6edaa  (unknown)
    @     0x2b699bb6ece4  (unknown)
    @     0x2b699bb6e6e6  (unknown)
    @     0x2b699bb71687  (unknown)
    @     0x2b699ca38930  caffe::ROIPoolingLayer<>::Backward_cpu()
    @           0x4644e5  caffe::Layer<>::Backward()
    @           0x469c31  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x46d14b  caffe::GradientChecker<>::CheckGradientExhaustive()
    @           0x6520f0  caffe::ROIPoolingLayerTest_TestGradient_Test<>::TestBody()
    @           0x6f6993  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x6ed5d7  testing::Test::Run()
    @           0x6ed67e  testing::TestInfo::Run()
    @           0x6ed785  testing::TestCase::Run()
    @           0x6f0ac8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x6f0d57  testing::UnitTest::Run()
    @           0x442a1a  main
    @     0x2b699d58cec5  (unknown)
    @           0x447a29  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by rbgirshick** [comment]
I've disabled the roi_pooling_layer CPU device test for now https://github.com/rbgirshick/caffe-fast-rcnn/commit/bcd9b4eadc7d8fbc433aeefd564e82ec63aaf69c. Better tests are a todo.

**Comment by Tingting-Chang** [comment]
Hi, @rbgirshick I do not know why I still get this error. 

[ RUN      ] ROIPoolingLayerTest/1.TestGradient
F0605 18:07:55.833154  9241 roi_pooling_layer.cpp:130] Not Implemented Yet
*** Check failure stack trace: ***
    @     0x2b907352adbd  google::LogMessage::Fail()
    @     0x2b907352cc5d  google::LogMessage::SendToLog()
    @     0x2b907352a9ac  google::LogMessage::Flush()
    @     0x2b907352d57e  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b9075558f20  caffe::ROIPoolingLayer<>::Backward_cpu()
    @           0x4601d5  caffe::Layer<>::Backward()
    @           0x463459  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x4a4816  caffe::ROIPoolingLayerTest_TestGradient_Test<>::TestBody()
    @           0x6cb453  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x6c20d7  testing::Test::Run()
    @           0x6c217e  testing::TestInfo::Run()
    @           0x6c2285  testing::TestCase::Run()
    @           0x6c55c8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x6c5857  testing::UnitTest::Run()
    @           0x4560f2  main
    @     0x2b907600af45  (unknown)
    @           0x45cdd9  (unknown)
Aborted (core dumped)
make: *** [runtest] Error 134
