### ISSUE TITLE
How to reproduce the experiment in the paper

### ISSUE THREAD

**Issue by naoto0804** [rbgirshick/fast-rcnn#62]
Hello.

I'm new to fast-rcnn, and I'd like to get the same mAP results in VOC2007 test as your paper in arxiv(http://arxiv.org/abs/1504.08083).
In the paper, it is said that mAP=66.9% when using a method called FRCN[our].

However, when I tried, I got 67.5% by running the command below.
(Of course, I read a instruction "Experiment scripts" in README.md and tried to follow them.)
./experiments/scripts/default_vgg16.sh 0

Is there any mistake or misunderstanding?

Thank you in advance.

**Comment by rbgirshick** [comment]
Please see the note about reproducing results "up to stochastic variation" [here](https://github.com/rbgirshick/fast-rcnn/#experiment-scripts).

Unfortunately I did not use a fixed random seed for the value of 66.9%. Subsequently, I fixed the rng seed in the code to make results reproducible. Performance is around mAP = 67.2% +/- 0.2 based on multiple runs with different seeds. I didn't have enough GPUs and time while preparing the paper to run each experiment multiple times. Ideally I would provide information on the mAP distribution for each experiment.

**Comment by naoto0804** [comment]
Thank you so much!!
