### ISSUE TITLE
matlab can be replaced by octave ?

### ISSUE THREAD

**Issue by wkentaro** [rbgirshick/fast-rcnn#74]
At [Usage](https://github.com/rbgirshick/fast-rcnn#usage) README says matlab is necessary for PASCAL VOC evaluation.
But I don't have matlab license so I'd like to use octave as substitution.

**Comment by sunshineatnoon** [comment]
I don't have matlab either, but I use dlib's selective search and wrote the evaluation code myself, you can also find a python evaluation at https://github.com/rbgirshick/fast-rcnn/pull/33.

**Comment by wkentaro** [comment]
@sunshineatnoon 
That's what I was looking for.
Thanks.
