### ISSUE TITLE
Running fast-rcnn on cpu.

### ISSUE THREAD

**Issue by frattezi** [rbgirshick/fast-rcnn#77]
Hi, I`m having issues to run the fast-rcnn demo on cpu mode, on caffe, when i run the  `make test` command i have errors related to GPU, it looks like you changed the code on `test_roi_pooling_layer.cpp`, is that right ? 
I tried also to run the fast-rcnn building caffe and pycaffe normally and I`m getting this:

 File "/home/frattezi/fast-rcnn/tools/../lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "/home/frattezi/fast-rcnn/tools/../lib/fast_rcnn/train.py", line 12, in <module>
    import roi_data_layer.roidb as rdl_roidb
  File "/home/frattezi/fast-rcnn/tools/../lib/roi_data_layer/roidb.py", line 12, in <module>
    import utils.cython_bbox
ImportError: No module named cython_bbox

Do I need to use a GPU to run the fast-rcnn?

**Comment by sid027** [comment]
Yes,I think.There are modules used which are only available in cuda.

**Comment by fengyuxi55** [comment]
@frattezi , I think you should go to $FRCN_ROOT/lib and do 'make' before you make caffe and pycaffe
The problem is there is module named cython_bbox

**Comment by frattezi** [comment]
@fengyuxi55  Thanks, i did that and it worked!

**Comment by indsak** [comment]
Hi,
 I successfully executed demo.py. But i am not able to train my own dataset.

./tools/train_faster_rcnn_alt_opt.py --net_name fish_classify --weights data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel 
Called with args:
Namespace(cfg_file=None, gpu_id=0, imdb_name='voc_2007_trainval', net_name='fish_classify', pretrained_model='data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel', set_cfgs=None)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Stage 1 RPN, init from ImageNet model
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Init model: data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel
Using config:
{'DATA_DIR': '/root/deep-learning/FRCNN/py-faster-rcnn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'default',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/root/deep-learning/FRCNN/py-faster-rcnn/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/root/deep-learning/FRCNN/py-faster-rcnn',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': False,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': False,
           'BBOX_REG': False,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': 'stage1',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': False}
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0608 16:24:47.054726  7419 common.cpp:66] **Cannot use GPU in CPU-only Caffe: check mode**.
*** Check failure stack trace: ***

**Comment by indsak** [comment]
Hi
 i started to train faster RCNN as per https://github.com/deboc/py-faster-rcnn/tree/master/help

When i try to train using the command
./tools/train_faster_rcnn_alt_opt.py --gpu 0 --net_name fishclassify --weights data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel --imdb fishclassify --cfg /home/fast-rcnn/py-faster-rcnn/config.yml

I am getting the following error
File "/fast-rcnn/py-faster-rcnn/tools/../lib/datasets/factory.py", line 46, in get_imdb
raise KeyError('Unknown dataset: {}'.format(name))

Any help on what might be causing this?
I had created fishclassify.py and fishclassify_eval.py under lib/datasets as well as modified factory.py
