### ISSUE TITLE
   roidb[i]['image'] = imdb.image_path_at(i)

### ISSUE THREAD

**Issue by athus1990** [rbgirshick/fast-rcnn#79]
Hi,
When I train the fast0rcnn on my own dataset I get this error while training.
It seems we are accessing the index image 500 even though train.txt has only 250 images.

File "./tools/train_net.py", line 85, in <module>
    roidb = get_training_roidb(imdb)
  File "/usr/local/fast-rcnn/tools/../lib/fast_rcnn/train.py", line 111, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/usr/local/fast-rcnn/tools/../lib/roi_data_layer/roidb.py", line 23, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range

**Comment by yileo19920925** [comment]
hi i met the same question did u make it ?

**Comment by IdiosyncraticDragon** [comment]
I thought this may be caused by the cache file, you can delete the specific cache files for your training data under the folder fast-rcnn-master/data/cache/, and try again

**Comment by yileo19920925** [comment]
@IdiosyncraticDragon thx! the solution is exactly what u said..~

**Comment by IdiosyncraticDragon** [comment]
@yileo19920925 you are welcome~~

**Comment by smasoudn** [comment]
I still have this issue, although I cleaned the cache folder.
The thing is that I get this error when I use few training data! Any  idea?

**Comment by zhongjunping** [comment]
hi, I also still have this problem, have you solved it? thx @smasoudn

**Comment by reddypruthvidhar** [comment]
I am facing the same problem, let me know if you figured out this @smasoudn @zhongjunping

**Comment by charan223** [comment]
clearing cache folder in data folder worked.

**Comment by andytung2019** [comment]
I did it, clear cache then OK
I think it run error because my training data set changed .

**Comment by jinhuan-hit** [comment]
@smasoudn @zhongjunping @reddypruthvidhar I still have the problem,although I have deleted the cache folder.I train the pretrained model which iteration is 240000 on my dataset.However,when it comes to iteration 241300,the problem occurs.Have you solved it?
