### ISSUE TITLE
Training including "negative" images

### ISSUE THREAD

**Issue by FangLinHe** [rbgirshick/fast-rcnn#82]
Hello all,

I am recently training on my own dataset and object classes.  Since my object is specific and very limited ranged, I would like to include some extra images not including any target objects, in order to reduce to false positive rate (i.e., detecting objects where no target objects actually shown).  However, I found the difficulty to do so due to the loss computation.  I would like to know if anyone has done so or has any suggestions on this issue?  I appreciate and look forward for any cool ideas!  Thank you.

**Comment by FangLinHe** [comment]
I just tried this way (but may not be trivial): For images without any target objects / annotation xml file, I make a "fake" class called fake_bg, and assign the whole image to this class.  The experimental results (qualitatively) show that it successfully reduces the false positive rate.  One may try it if they are interested.

**Comment by xiaoxiongli** [comment]
I think you'd better to dig in the Faster RCNN source code and you will find it is easy to add negative samples to the net.

**Comment by aichase** [comment]
@xiaoxiongli Can you elaborate on how to add negative samples to the network? I looked at the source code and found it a bit difficult. Thanks.
