### ISSUE TITLE
tools/train_svms.py bug

### ISSUE THREAD

**Issue by kt892790499** [rbgirshick/fast-rcnn#84]
Hi, @rbgirshick .

I think the tools/train_svms.py line 346 should change
imdb.append_flipped_roidb() to imdb.append_flipped_images()
pls have a check, thanks.

**Comment by debidatta** [comment]
I agree with this.

**Comment by rbgirshick** [comment]
Thanks for catching this typo. I missed it after refactoring. It's fixed in https://github.com/rbgirshick/fast-rcnn/commit/364344b6658b98558c2a447fb472bf3e6f0421bc.
