### ISSUE TITLE
Compiling the fast-rcnn failed

### ISSUE THREAD

**Issue by wkal** [rbgirshick/fast-rcnn#97]
Hello, every Fast-rcnn player! I faced a problem while compiling the fast r-cnn, g++ compiler reports a function is not defined: caffe.cpp:(.text+0x20b): undefined reference to `caffe::Net::Net(std::string const&, caffe::Phase)'. Have anyone meet this problem too? And could you give me a hand? Thanks very much! The code is runing on Ubuntu14.04 x64 with g++4.8.4 compiling.

The detailed error information:
############################################################
.build_release/tools/caffe.o: In function test()': caffe.cpp:(.text+0x20b): undefined reference tocaffe::Net::Net(std::string const&, caffe::Phase)'
.build_release/tools/caffe.o: In function train()': caffe.cpp:(.text+0x1395): undefined reference tocaffe::Caffe::singleton_'
.build_release/tools/caffe.o: In function time()': caffe.cpp:(.text+0x196c): undefined reference tocaffe::Net::Net(std::string const&, caffe::Phase)'
.build_release/tools/caffe.o: In function caffe::Caffe::Get()': caffe.cpp:(.text._ZN5caffe5Caffe3GetEv[_ZN5caffe5Caffe3GetEv]+0x7): undefined reference tocaffe::Caffe::singleton_'
.build_release/tools/caffe.o: In function caffe::Solver<float>* caffe::GetSolver<float>(caffe::SolverParameter const&)': caffe.cpp:(.text._ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE[_ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE]+0x4a): undefined reference tocaffe::Solver::Solver(caffe::SolverParameter const&)'
caffe.cpp:(.text.ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE[_ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE]+0x1b4): undefined reference to caffe::Solver<float>::Solver(caffe::SolverParameter const&)' caffe.cpp:(.text._ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE[_ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE]+0x2e4): undefined reference tocaffe::Solver::Solver(caffe::SolverParameter const&)'
caffe.cpp:(.text._ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE[_ZN5caffe9GetSolverIfEEPNS_6SolverIT_EERKNS_15SolverParameterE]+0x3d4): undefined reference to caffe::Solver<float>::Solver(caffe::SolverParameter const&)' collect2: error: ld returned 1 exit status .build_release/tools/extract_features.o: In functioncaffe::Caffe::Get()':
extract_features.cpp:(.text._ZN5caffe5Caffe3GetEv[_ZN5caffe5Caffe3GetEv]+0x7): undefined reference to `caffe::Caffe::singleton'
.build_release/tools/extract_features.o: In function int feature_extraction_pipeline<float>(int, char**)': extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0xa8): undefined reference tocaffe::Caffe::singleton_'
extract_features.cpp:(.text.Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x114): undefined reference to caffe::Net<float>::Net(std::string const&, caffe::Phase)' collect2: error: ld returned 1 exit status make: *** [.build_release/tools/extract_features.bin] Error 1 make: *** Waiting for unfinished jobs.... make: *** [.build_release/tools/caffe.bin] Error 1 .build_release/tools/convert_imageset.o: In functionvoid caffe::shuffle<__gnu_cxx::__normal_iterator, std::vector, std::allocator > > > >(__gnu_cxx::__normal_iterator, std::vector, std::allocator > > >, __gnu_cxx::__normal_iterator*, std::vector, std::allocator > > >)':
convert_imageset.cpp:(.text._ZN5caffe7shuffleIN9__gnu_cxx17__normal_iteratorIPSt4pairISsiESt6vectorIS4_SaIS4_EEEEEEvT_SA[ZN5caffe7shuffleIN9__gnu_cxx17__normal_iteratorIPSt4pairISsiESt6vectorIS4_SaIS4_EEEEEEvT_SA]+0x14): undefined reference to `caffe::Caffe::singleton_'
collect2: error: ld returned 1 exit status
/usr/bin/ld: .build_release/examples/cpp_classification/classification.o: undefined reference to symbol '_ZN2cv6imreadERKNS_6StringEi'
//usr/local/lib/libopencv_imgcodecs.so.3.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/cpp_classification/classification.bin] Error 1
make: *** [.build_release/tools/convert_imageset.bin] Error 1

**Comment by rvaen** [comment]
do you fix it , i have same error , how to fix it ?
